```yml
stages:
  - 🛠 Build

image: ghcr.io/webees/kaniko-maven3-jdk8:v1.0.0

variables:
  CI_DEBUG_TRACE: "false"
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
    -Dmaven.wagon.http.ssl.insecure=true
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true

cache:
  paths:
    - .m2/repository

before_script:
  - cat /etc/hosts
  - echo ${CI_PROJECT_DIR}
  # - ls /etc/gitlab-runner/certs
  # - cp /etc/gitlab-runner/certs/ca.crt /usr/local/share/ca-certificates/ca.crt
  # - update-ca-certificates --fresh
  # - echo $MAVEN_CONFIG
  # - cp -r $CI_PROJECT_DIR/.m2 $MAVEN_CONFIG

build:
  stage: 🛠 Build
  only:
    - master
    - release
  variables:
    CI_DEBUG_TRACE: "false"
  script:
    - mvn $MAVEN_CLI_OPTS clean package
    # - mvn $MAVEN_CLI_OPTS deploy -s ci_settings.xml -DskipTests
    - ls -a
    # admin
    - MOUDLE_NAME=admin
    - CONTEXT_DIR=${CI_PROJECT_DIR}/${MOUDLE_NAME}
    - IMAGE_NAME=${CI_REGISTRY_IMAGE}/${MOUDLE_NAME}
    - executor --context "${CONTEXT_DIR}" --dockerfile "${CONTEXT_DIR}/Dockerfile" --destination "${IMAGE_NAME}:${CI_COMMIT_BRANCH}" --destination "${IMAGE_NAME}:${CI_COMMIT_BRANCH}-${CI_COMMIT_SHA}" --snapshot-mode=redo --skip-tls-verify
```
